---
title: |
  | Diateam: SCAD\@COPS
  | A Hybrid Network Intrusion Detection System
author: "Lisa MALIPHOL"
date: July 2015
output:
  pdf_document:
    keep_tex: yes
---
```{r, echo=FALSE, message=FALSE}
#require(TRSbook)
require(data.table)
require(igraph)
#require(ggplot2)
#require(gplots)
#require(lattice)
#require(dplyr)
#require(plyr)
#require(reshape2)
#require(RColorBrewer)
#require(png)
#require(grid)
#require(gridExtra)
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
# Load data from save(sewTCPConvDT, sewEndPtsDT, file="sewConvEnd.Rda")
load("/home/lisa/rDia/sewConvEnd.Rda")
```

\pagebreak


```{r, echo=FALSE, message=FALSE, warning, fig.align='center'}
 g1 <- graph.data.frame(sewTCPConvDT[,.(Address.A, Address.B, Packets, Bytes, Duration)], directed=FALSE)
 gAdjMtx <- get.adjacency(g1)  # adjacency mtx
 gAdj <- graph.adjacency(gAdjMtx, mode="undirected", weighted=TRUE)
 V(gAdj)$size <- degree(gAdj)*40  # node size according to degree of centrality
 eW <- E(gAdj)$weight  # edge weights
 eW <- ceiling(eW/max(eW)*55)
 eW[eW>10] <- 10
plot.igraph(gAdj, main="Graph of SCADA Network", edge.width=eW)


# g2 <- ggplot(sewTCPConvDT, aes(x = factor(0), y = Bytes/1e6)) +
#   geom_boxplot(fill="darkorchid3") + xlab("") + scale_x_discrete(breaks = NULL) +
#   facet_grid(~Address.A) +
#   ggtitle("Boxplot of Packet Size by Source") +
#   ylab("MBytes") +
#   theme( plot.margin = unit(c(2,0,1,0), "cm") )
# 
# grid.arrange(g1, g2, nrow(2))
# 
# rm(g1,g2, gAdjMtx, gAdj, eW)
invisible(dev.off())
```

